/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package general;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author rjuni
 */
public class TelaJogo extends javax.swing.JFrame {

    private Jogo jogo;
    private int rodada;
    private int limiteVez;
    private int total1;
    private int total2;
    private int total3;
    private int total4;

    /**
     * Creates new form TelaMain
     */
    public TelaJogo(Jogo jogo) {
        initComponents();

        this.jogo = jogo;
        rodada = 13;
        limiteVez = 3;
        lblRodada.setText("Rodada: " + rodada);
        ArrayList<Jogador> jg = new ArrayList();
        jg = jogo.getJogadores();

        if (jg.size() == 2) {
            Jogador jog1 = jg.get(0);
            Jogador jog2 = jg.get(1);
            nomeJ1.setText(jog1.getNome());
            nomeJ2.setText(jog2.getNome());

        }
        if (jg.size() == 3) {
            Jogador jog3 = jg.get(2);
            Jogador jog1 = jg.get(0);
            Jogador jog2 = jg.get(1);
            nomeJ1.setText(jog1.getNome());
            nomeJ2.setText(jog2.getNome());
            nomeJ3.setText(jog3.getNome());

        }
        if (jg.size() == 4) {
            Jogador jog1 = jg.get(0);
            Jogador jog2 = jg.get(1);
            Jogador jog3 = jg.get(2);
            Jogador jog4 = jg.get(3);
            nomeJ1.setText(jog1.getNome());
            nomeJ2.setText(jog2.getNome());
            nomeJ3.setText(jog3.getNome());
            nomeJ4.setText(jog4.getNome());

        }
        jogo.setVez(1);
        vezJogador.setText("Vez do jogador: " + jogo.getVez());
        jogo.setRodada();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        painelVez = new javax.swing.JPanel();
        dado2 = new javax.swing.JRadioButton();
        dado3 = new javax.swing.JRadioButton();
        aremessarDados = new javax.swing.JButton();
        dado5 = new javax.swing.JRadioButton();
        dado1 = new javax.swing.JRadioButton();
        relancarDados = new javax.swing.JButton();
        dado4 = new javax.swing.JRadioButton();
        vezJogador = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        boxJogada = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnFinaliza = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        nomeJ1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeJ4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nomeJ2 = new javax.swing.JLabel();
        nomeJ3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblRodada = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tabelaPontos = new javax.swing.JTable();

        jTextField4.setText("jTextField4");

        jLabel5.setText("jLabel5");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable4);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable5);

        jScrollPane7.setPreferredSize(new java.awt.Dimension(50, 50));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable6);

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelVez.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        dado2.setText("0");
        dado2.setFocusable(false);
        dado2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dado2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        dado3.setText("0");
        dado3.setFocusable(false);
        dado3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dado3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        aremessarDados.setText("Arremessar os dados");
        aremessarDados.setFocusable(false);
        aremessarDados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aremessarDados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        aremessarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aremessarDadosActionPerformed(evt);
            }
        });

        dado5.setText("0");
        dado5.setFocusable(false);
        dado5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dado5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        dado1.setText("0");
        dado1.setFocusable(false);
        dado1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dado1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        relancarDados.setText("Relançar os dados");
        relancarDados.setEnabled(false);
        relancarDados.setFocusable(false);
        relancarDados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        relancarDados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        relancarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relancarDadosActionPerformed(evt);
            }
        });

        dado4.setText("0");
        dado4.setFocusable(false);
        dado4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dado4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        vezJogador.setText("jLabel8");

        javax.swing.GroupLayout painelVezLayout = new javax.swing.GroupLayout(painelVez);
        painelVez.setLayout(painelVezLayout);
        painelVezLayout.setHorizontalGroup(
            painelVezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelVezLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelVezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelVezLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(vezJogador))
                    .addComponent(aremessarDados)
                    .addGroup(painelVezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(painelVezLayout.createSequentialGroup()
                            .addComponent(dado2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(dado1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dado3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(dado4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dado5))
                        .addComponent(relancarDados)))
                .addContainerGap())
        );
        painelVezLayout.setVerticalGroup(
            painelVezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelVezLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(vezJogador)
                .addGap(18, 18, 18)
                .addComponent(aremessarDados)
                .addGap(63, 63, 63)
                .addGroup(painelVezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dado3)
                    .addComponent(dado4)
                    .addComponent(dado2)
                    .addComponent(dado1)
                    .addComponent(dado5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(relancarDados)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        boxJogada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jogada de 1", "Jogada de 2", "Jogada de 3", "Jogada de 4", "Jogada de 5", "Jogada de 6", "Trinca(T)", "Quadra(Q)", "Full-hand(F)", "Squencia alta(S+)", "Sequencia baixa(S-)", "General(G)", "Jogada aleatoria(X)" }));

        jLabel6.setText("Selecione a jogada:");

        btnFinaliza.setText("Finalizar jogada");
        btnFinaliza.setEnabled(false);
        btnFinaliza.setFocusable(false);
        btnFinaliza.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFinaliza.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFinaliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFinaliza)
                    .addComponent(jLabel6)
                    .addComponent(boxJogada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxJogada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159)
                .addComponent(btnFinaliza)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogadores"));

        nomeJ1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nomeJ1.setText("------------");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Jogador 4");

        nomeJ4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nomeJ4.setText("------------");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Jogador 1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Jogador 2");

        nomeJ2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nomeJ2.setText("------------");

        nomeJ3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nomeJ3.setText("------------");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Jogador 3");

        lblRodada.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblRodada.setText("jLabel8");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(nomeJ1))
                                .addGap(79, 79, 79)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeJ2)
                                    .addComponent(jLabel1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(nomeJ3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeJ4)
                                    .addComponent(jLabel3)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(lblRodada)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeJ2)
                    .addComponent(nomeJ1))
                .addGap(18, 18, 18)
                .addComponent(lblRodada)
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeJ4)
                    .addComponent(nomeJ3))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        tabelaPontos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"2",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"3",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"4",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"5",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"6",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"T",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"Q",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"F",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"S+",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"S-",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"G",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"X",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"TOTAL",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)}
            },
            new String [] {
                "Jogadas", "Jogador 1", "Jogador 2", "Jogador 3", "Jogador 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tabelaPontos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelVez, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelVez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aremessarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aremessarDadosActionPerformed
        Dado dad = new Dado();
        dado1.setText(Integer.toString(dad.darValor()));
        dado2.setText(Integer.toString(dad.darValor()));
        dado3.setText(Integer.toString(dad.darValor()));
        dado4.setText(Integer.toString(dad.darValor()));
        dado5.setText(Integer.toString(dad.darValor()));
        relancarDados.setEnabled(rootPaneCheckingEnabled);
        aremessarDados.setEnabled(false);
        btnFinaliza.setEnabled(true);
    }//GEN-LAST:event_aremessarDadosActionPerformed

    private void relancarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relancarDadosActionPerformed
        if (limiteVez != 0) {
            Dado dad = new Dado();

            if (dado1.isSelected()) {
                dado1.setText(Integer.toString(dad.darValor()));
                dado1.setSelected(false);
            }
            if (dado2.isSelected()) {
                dado2.setText(Integer.toString(dad.darValor()));
                dado2.setSelected(false);
            }
            if (dado3.isSelected()) {
                dado3.setText(Integer.toString(dad.darValor()));
                dado3.setSelected(false);
            }
            if (dado4.isSelected()) {
                dado4.setText(Integer.toString(dad.darValor()));
                dado4.setSelected(false);
            }
            if (dado5.isSelected()) {
                dado5.setText(Integer.toString(dad.darValor()));
                dado5.setSelected(false);
            }
            limiteVez = limiteVez - 1;
        }
        if (limiteVez == 0) {
            relancarDados.setEnabled(false);
        }

    }//GEN-LAST:event_relancarDadosActionPerformed

    private void btnFinalizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizaActionPerformed

        ArrayList<Integer> dados = new ArrayList();
        //dados.add(Integer.parseInt(dado1.getText()));
        //dados.add(Integer.parseInt(dado2.getText()));
        //dados.add(Integer.parseInt(dado3.getText()));
        //dados.add(Integer.parseInt(dado4.getText()));
        //dados.add(Integer.parseInt(dado5.getText()));
        dados.add(6);
        dados.add(6);
        dados.add(6);
        dados.add(5);
        dados.add(5);
        Collections.sort(dados);
        JOptionPane.showMessageDialog(null, "" + dados.get(0) + "" + dados.get(1) + "" + dados.get(2) + "" + dados.get(3) + "" + dados.get(4));

        if (rodada > 0) {
            if (boxJogada.getItemAt(0).equals(boxJogada.getSelectedItem())) {
                tratarJogadaP(1, 0, dados);

            }
            if (boxJogada.getItemAt(1).equals(boxJogada.getSelectedItem())) {
                tratarJogadaP(2, 1, dados);
            }
            if (boxJogada.getItemAt(2).equals(boxJogada.getSelectedItem())) {
                tratarJogadaP(3, 2, dados);
            }
            if (boxJogada.getItemAt(3).equals(boxJogada.getSelectedItem())) {
                tratarJogadaP(4, 3, dados);
            }
            if (boxJogada.getItemAt(4).equals(boxJogada.getSelectedItem())) {
                tratarJogadaP(5, 4, dados);
            }
            if (boxJogada.getItemAt(5).equals(boxJogada.getSelectedItem())) {
                tratarJogadaP(6, 5, dados);
            }
            if (boxJogada.getItemAt(6).equals(boxJogada.getSelectedItem())) {
                boolean tresIguais = false;
                int soma = 0;

                for (int i = 0; i < dados.size(); i++) {
                    soma += dados.get(i);

                    if (i <= 2) {
                        if (dados.get(i).equals(dados.get(i + 1))) {
                            //JOptionPane.showMessageDialog(null, dados.get(i)+""+dados.get(i+1));
                            if (dados.get(i).equals(dados.get(i + 2))) {
                                //JOptionPane.showMessageDialog(null, dados.get(i)+" "+dados.get(i+1)+""+dados.get(i+2));
                                tresIguais = true;

                            }
                        }

                    }
                }

                if (tresIguais == false) {
                    JOptionPane.showMessageDialog(null, "Jogada Invalida");
                } else {

                    tabelaPontos.setValueAt(soma + (Integer) (tabelaPontos.getValueAt(0, jogo.getVez())), 6, jogo.getVez());
                    tabelaPontos.setValueAt(verificarJogador(soma), 13, jogo.getVez());
                    resetarRodada();
                }

            }
            if (boxJogada.getItemAt(7).equals(boxJogada.getSelectedItem())) {
                boolean quatroIguais = false;
                int soma = 0;

                for (int i = 0; i < dados.size(); i++) {
                    soma += dados.get(i);

                    if (i <= 1) {
                        if (dados.get(i).equals(dados.get(i + 1))) {
                            //JOptionPane.showMessageDialog(null, dados.get(i)+""+dados.get(i+1));
                            if (dados.get(i).equals(dados.get(i + 2))) {
                                //JOptionPane.showMessageDialog(null, dados.get(i)+" "+dados.get(i+1)+""+dados.get(i+2));
                                if (dados.get(i).equals(dados.get(i + 3))) {
                                    quatroIguais = true;
                                }

                            }
                        }

                    }
                }

                if (quatroIguais == false) {
                    JOptionPane.showMessageDialog(null, "Jogada Invalida");
                } else {

                    tabelaPontos.setValueAt(soma + (Integer) (tabelaPontos.getValueAt(0, jogo.getVez())), 7, jogo.getVez());
                    tabelaPontos.setValueAt(verificarJogador(soma), 13, jogo.getVez());
                    resetarRodada();
                }

            }
            if (boxJogada.getItemAt(8).equals(boxJogada.getSelectedItem())) {
                boolean trinca = false;
                boolean par = false;

                for (int i = 0; i < dados.size(); i++) {

                    if (i <= 2) {
                        if (dados.get(i).equals(dados.get(i + 1))) {
                            //JOptionPane.showMessageDialog(null, dados.get(i)+""+dados.get(i+1));
                            if (dados.get(i).equals(dados.get(i + 2))) {
                                //JOptionPane.showMessageDialog(null, dados.get(i)+" "+dados.get(i+1)+""+dados.get(i+2));
                                trinca = true;

                            }
                        }

                    } else if(i == 3) {
                        if (dados.get(i).equals(dados.get(i + 1))) {
                            par = true;
                        }
                    }
                }
                if (trinca == false) {
                    JOptionPane.showMessageDialog(null, "Jogada Invalida");
                } else if (trinca == true || par == true) {

                    tabelaPontos.setValueAt(25, 8, jogo.getVez());
                    tabelaPontos.setValueAt(verificarJogador(25), 13, jogo.getVez());
                    resetarRodada();
                }

            }
            if (boxJogada.getItemAt(9).equals(boxJogada.getSelectedItem())) {

            }
            if (boxJogada.getItemAt(10).equals(boxJogada.getSelectedItem())) {

            }
            if (boxJogada.getItemAt(11).equals(boxJogada.getSelectedItem())) {

            }
            if (boxJogada.getItemAt(12).equals(boxJogada.getSelectedItem())) {

            }

        }
        if (rodada == 0) {
            aremessarDados.setEnabled(false);
            relancarDados.setEnabled(false);
            btnFinaliza.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Jogo finalizado!");
        }
    }//GEN-LAST:event_btnFinalizaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    private void resetarDados() {
        dado1.setText(Integer.toString(0));
        dado2.setText(Integer.toString(0));
        dado3.setText(Integer.toString(0));
        dado4.setText(Integer.toString(0));
        dado5.setText(Integer.toString(0));
    }

    private void resetarRodada() {
        limiteVez = 3;
        aremessarDados.setEnabled(true);
        relancarDados.setEnabled(false);
        btnFinaliza.setEnabled(false);
        vezJogador.setText("Vez do jogador: " + jogo.controladorMain());
        rodada = rodada - 1;
        lblRodada.setText("Rodada: " + rodada);
        resetarDados();

    }

    private int selecionarColuna(JTable table, String name) {
        for (int i = 0; i < table.getColumnCount(); ++i) {
            if (table.getColumnName(i).equals(name)) {
                return i;
            }
        }
        return -1;
    }

    private Integer verificarJogador(int pt) {
        if (jogo.getVez() == 1) {
            total1 = total1 + pt;
            return total1;
        }
        if (jogo.getVez() == 2) {
            total2 = total2 + pt;
            return total2;
        }
        if (jogo.getVez() == 3) {
            total3 = total3 + pt;
            return total3;
        }
        if (jogo.getVez() == 4) {
            total4 = total4 + pt;
            return total4;
        }
        return 0;
    }

    private void tratarJogadaP(int j, int i0, ArrayList<Integer> dados) {

        int pt = 0;
        for (int i = 0; i < dados.size(); i++) {
            if (dados.get(i) == j) {
                pt += (1 * j);
            }
        }
        if (pt == 0) {
            JOptionPane.showMessageDialog(null, "Jogada invalida! ");
        } else {

            tabelaPontos.setValueAt(pt + (Integer) (tabelaPontos.getValueAt(0, jogo.getVez())), i0, jogo.getVez());
            tabelaPontos.setValueAt(verificarJogador(pt), 13, jogo.getVez());
            resetarRodada();
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aremessarDados;
    private javax.swing.JComboBox<String> boxJogada;
    private javax.swing.JButton btnFinaliza;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton dado1;
    private javax.swing.JRadioButton dado2;
    private javax.swing.JRadioButton dado3;
    private javax.swing.JRadioButton dado4;
    private javax.swing.JRadioButton dado5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblRodada;
    private javax.swing.JLabel nomeJ1;
    private javax.swing.JLabel nomeJ2;
    private javax.swing.JLabel nomeJ3;
    private javax.swing.JLabel nomeJ4;
    private javax.swing.JPanel painelVez;
    private javax.swing.JButton relancarDados;
    private javax.swing.JTable tabelaPontos;
    private javax.swing.JLabel vezJogador;
    // End of variables declaration//GEN-END:variables

}
